const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "admin-web", "src");

function write(rel, body) {
  const full = path.join(root, rel);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, body, { encoding: "utf8" });
  console.log("  \u2713 " + rel);
}

// ============ src/api/client.ts ============
write("api/client.ts", [
  'import axios, { AxiosError, InternalAxiosRequestConfig } from "axios";',
  '',
  'const ACCESS_KEY = "ea.accessToken";',
  'const REFRESH_KEY = "ea.refreshToken";',
  '',
  'export const authStorage = {',
  '  getAccess: () => localStorage.getItem(ACCESS_KEY),',
  '  getRefresh: () => localStorage.getItem(REFRESH_KEY),',
  '  setTokens: (access: string, refresh: string) => {',
  '    localStorage.setItem(ACCESS_KEY, access);',
  '    localStorage.setItem(REFRESH_KEY, refresh);',
  '  },',
  '  clear: () => {',
  '    localStorage.removeItem(ACCESS_KEY);',
  '    localStorage.removeItem(REFRESH_KEY);',
  '  },',
  '};',
  '',
  'export const api = axios.create({',
  '  baseURL: "/api",',
  '  headers: { "Content-Type": "application/json" },',
  '});',
  '',
  '// ---- Request: подставить accessToken ----',
  'api.interceptors.request.use((config: InternalAxiosRequestConfig) => {',
  '  const token = authStorage.getAccess();',
  '  if (token) {',
  '    config.headers = config.headers ?? {};',
  '    config.headers.Authorization = `Bearer ${token}`;',
  '  }',
  '  return config;',
  '});',
  '',
  '// ---- Response: на 401 — попытка refresh один раз ----',
  'let refreshing: Promise<string | null> | null = null;',
  '',
  'async function tryRefresh(): Promise<string | null> {',
  '  const refresh = authStorage.getRefresh();',
  '  if (!refresh) return null;',
  '  try {',
  '    const { data } = await axios.post("/api/auth/refresh", { refreshToken: refresh });',
  '    if (data?.accessToken && data?.refreshToken) {',
  '      authStorage.setTokens(data.accessToken, data.refreshToken);',
  '      return data.accessToken as string;',
  '    }',
  '    return null;',
  '  } catch {',
  '    return null;',
  '  }',
  '}',
  '',
  'api.interceptors.response.use(',
  '  (r) => r,',
  '  async (error: AxiosError) => {',
  '    const original = error.config as InternalAxiosRequestConfig & { _retried?: boolean };',
  '    if (error.response?.status === 401 && original && !original._retried) {',
  '      original._retried = true;',
  '      if (!refreshing) {',
  '        refreshing = tryRefresh().finally(() => { refreshing = null; });',
  '      }',
  '      const newAccess = await refreshing;',
  '      if (newAccess) {',
  '        original.headers = original.headers ?? {};',
  '        original.headers.Authorization = `Bearer ${newAccess}`;',
  '        return api.request(original);',
  '      }',
  '      authStorage.clear();',
  '      window.dispatchEvent(new Event("auth:logout"));',
  '    }',
  '    return Promise.reject(error);',
  '  },',
  ');',
  '',
].join("\n"));

// ============ src/auth/AuthContext.tsx ============
write("auth/AuthContext.tsx", [
  'import { createContext, useContext, useEffect, useState, ReactNode } from "react";',
  'import { api, authStorage } from "../api/client";',
  '',
  'export type Role = "director" | "admin" | "animator";',
  '',
  'export type User = {',
  '  id: string;',
  '  role: Role;',
  '  firstName: string;',
  '  lastName: string;',
  '  phone: string;',
  '  email: string | null;',
  '  status: "active" | "blocked" | "invited";',
  '};',
  '',
  'type AuthContextValue = {',
  '  user: User | null;',
  '  loading: boolean;',
  '  login: (phone: string, password: string) => Promise<void>;',
  '  logout: () => void;',
  '};',
  '',
  'const AuthContext = createContext<AuthContextValue | null>(null);',
  '',
  'export function AuthProvider({ children }: { children: ReactNode }) {',
  '  const [user, setUser] = useState<User | null>(null);',
  '  const [loading, setLoading] = useState(true);',
  '',
  '  // Восстановление сессии при старте',
  '  useEffect(() => {',
  '    let cancelled = false;',
  '    (async () => {',
  '      if (!authStorage.getAccess()) {',
  '        setLoading(false);',
  '        return;',
  '      }',
  '      try {',
  '        const { data } = await api.get<{ user: User }>("/auth/me");',
  '        if (!cancelled) setUser(data.user);',
  '      } catch {',
  '        authStorage.clear();',
  '      } finally {',
  '        if (!cancelled) setLoading(false);',
  '      }',
  '    })();',
  '    return () => { cancelled = true; };',
  '  }, []);',
  '',
  '  // Реакция на принудительный logout из axios-интерсептора',
  '  useEffect(() => {',
  '    const onLogout = () => setUser(null);',
  '    window.addEventListener("auth:logout", onLogout);',
  '    return () => window.removeEventListener("auth:logout", onLogout);',
  '  }, []);',
  '',
  '  const login = async (phone: string, password: string) => {',
  '    const { data } = await api.post<{ user: User; accessToken: string; refreshToken: string }>(',
  '      "/auth/login",',
  '      { phone, password },',
  '    );',
  '    if (data.user.role !== "director" && data.user.role !== "admin") {',
  '      throw new Error("\u0414\u043E\u0441\u0442\u0443\u043F \u0442\u043E\u043B\u044C\u043A\u043E \u0434\u043B\u044F \u0434\u0438\u0440\u0435\u043A\u0442\u043E\u0440\u0430 \u0438 \u0430\u0434\u043C\u0438\u043D\u0430");',
  '    }',
  '    authStorage.setTokens(data.accessToken, data.refreshToken);',
  '    setUser(data.user);',
  '  };',
  '',
  '  const logout = () => {',
  '    authStorage.clear();',
  '    setUser(null);',
  '  };',
  '',
  '  return (',
  '    <AuthContext.Provider value={{ user, loading, login, logout }}>',
  '      {children}',
  '    </AuthContext.Provider>',
  '  );',
  '}',
  '',
  'export function useAuth() {',
  '  const ctx = useContext(AuthContext);',
  '  if (!ctx) throw new Error("useAuth \u0434\u043E\u043B\u0436\u0435\u043D \u0431\u044B\u0442\u044C \u0432\u043D\u0443\u0442\u0440\u0438 <AuthProvider>");',
  '  return ctx;',
  '}',
  '',
].join("\n"));

// ============ src/pages/LoginPage.tsx ============
write("pages/LoginPage.tsx", [
  'import { FormEvent, useState } from "react";',
  'import { Navigate } from "react-router-dom";',
  'import { useAuth } from "../auth/AuthContext";',
  '',
  'export default function LoginPage() {',
  '  const { user, login } = useAuth();',
  '  const [phone, setPhone] = useState("");',
  '  const [password, setPassword] = useState("");',
  '  const [error, setError] = useState<string | null>(null);',
  '  const [loading, setLoading] = useState(false);',
  '',
  '  if (user) return <Navigate to="/" replace />;',
  '',
  '  const onSubmit = async (e: FormEvent) => {',
  '    e.preventDefault();',
  '    setError(null);',
  '    setLoading(true);',
  '    try {',
  '      await login(phone.trim(), password);',
  '    } catch (err: any) {',
  '      const msg =',
  '        err?.response?.data?.error ??',
  '        err?.message ??',
  '        "\u041D\u0435 \u0443\u0434\u0430\u043B\u043E\u0441\u044C \u0432\u043E\u0439\u0442\u0438";',
  '      setError(msg);',
  '    } finally {',
  '      setLoading(false);',
  '    }',
  '  };',
  '',
  '  return (',
  '    <div className="min-h-screen flex items-center justify-center p-6 bg-gray-100">',
  '      <form',
  '        onSubmit={onSubmit}',
  '        className="bg-white rounded-2xl shadow-md p-8 w-full max-w-sm"',
  '      >',
  '        <div className="text-center mb-6">',
  '          <div className="text-2xl font-extrabold text-primary">Event Agency</div>',
  '          <div className="text-sm text-gray-500 mt-1">\u0412\u0445\u043E\u0434 \u0432 \u0430\u0434\u043C\u0438\u043D-\u043F\u0430\u043D\u0435\u043B\u044C</div>',
  '        </div>',
  '',
  '        <label className="block text-sm font-medium text-gray-700 mb-1">\u0422\u0435\u043B\u0435\u0444\u043E\u043D</label>',
  '        <input',
  '          type="tel"',
  '          autoComplete="tel"',
  '          value={phone}',
  '          onChange={(e) => setPhone(e.target.value)}',
  '          placeholder="+7..."',
  '          className="w-full border border-gray-300 rounded-lg px-3 py-2 mb-4 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"',
  '          required',
  '        />',
  '',
  '        <label className="block text-sm font-medium text-gray-700 mb-1">\u041F\u0430\u0440\u043E\u043B\u044C</label>',
  '        <input',
  '          type="password"',
  '          autoComplete="current-password"',
  '          value={password}',
  '          onChange={(e) => setPassword(e.target.value)}',
  '          className="w-full border border-gray-300 rounded-lg px-3 py-2 mb-4 focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent"',
  '          required',
  '        />',
  '',
  '        {error ? (',
  '          <div className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg px-3 py-2 mb-4">',
  '            {error}',
  '          </div>',
  '        ) : null}',
  '',
  '        <button',
  '          type="submit"',
  '          disabled={loading}',
  '          className="w-full bg-primary hover:bg-primaryDark disabled:opacity-60 text-white font-semibold py-2.5 rounded-lg transition"',
  '        >',
  '          {loading ? "\u0412\u0445\u043E\u0436\u0443\u2026" : "\u0412\u043E\u0439\u0442\u0438"}',
  '        </button>',
  '      </form>',
  '    </div>',
  '  );',
  '}',
  '',
].join("\n"));

// ============ src/pages/PlaceholderPage.tsx ============
write("pages/PlaceholderPage.tsx", [
  'export default function PlaceholderPage({ title, note }: { title: string; note?: string }) {',
  '  return (',
  '    <div>',
  '      <h1 className="text-2xl font-bold text-gray-900">{title}</h1>',
  '      <p className="text-sm text-gray-500 mt-2">',
  '        {note ?? "\u0420\u0430\u0437\u0434\u0435\u043B \u0432 \u0440\u0430\u0437\u0440\u0430\u0431\u043E\u0442\u043A\u0435"}',
  '      </p>',
  '    </div>',
  '  );',
  '}',
  '',
].join("\n"));

// ============ src/layouts/AppLayout.tsx ============
write("layouts/AppLayout.tsx", [
  'import { NavLink, Outlet, useNavigate } from "react-router-dom";',
  'import { useAuth } from "../auth/AuthContext";',
  '',
  'const NAV = [',
  '  { to: "/orders", label: "\u0417\u0430\u043A\u0430\u0437\u044B", icon: "\uD83D\uDCC5" },',
  '  { to: "/clients", label: "\u041A\u043B\u0438\u0435\u043D\u0442\u044B", icon: "\uD83D\uDC65" },',
  '  { to: "/catalog", label: "\u0421\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A\u0438", icon: "\uD83C\uDFAD" },',
  '  { to: "/finance", label: "\u0424\u0438\u043D\u0430\u043D\u0441\u044B", icon: "\uD83D\uDCB0" },',
  '];',
  '',
  'export default function AppLayout() {',
  '  const { user, logout } = useAuth();',
  '  const navigate = useNavigate();',
  '',
  '  const onLogout = () => {',
  '    logout();',
  '    navigate("/login", { replace: true });',
  '  };',
  '',
  '  return (',
  '    <div className="min-h-screen flex bg-gray-100">',
  '      {/* Sidebar */}',
  '      <aside className="w-60 bg-white border-r border-gray-200 flex flex-col">',
  '        <div className="px-5 py-5 border-b border-gray-100">',
  '          <div className="text-lg font-extrabold text-primary">Event Agency</div>',
  '          <div className="text-xs text-gray-400 mt-0.5">Admin</div>',
  '        </div>',
  '',
  '        <nav className="flex-1 px-3 py-4 space-y-1">',
  '          {NAV.map((item) => (',
  '            <NavLink',
  '              key={item.to}',
  '              to={item.to}',
  '              className={({ isActive }) =>',
  '                [',
  '                  "flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition",',
  '                  isActive',
  '                    ? "bg-primary text-white"',
  '                    : "text-gray-700 hover:bg-gray-100",',
  '                ].join(" ")',
  '              }',
  '            >',
  '              <span className="text-base">{item.icon}</span>',
  '              <span>{item.label}</span>',
  '            </NavLink>',
  '          ))}',
  '        </nav>',
  '',
  '        <div className="p-3 border-t border-gray-100">',
  '          <div className="text-xs text-gray-500 px-2 mb-2">',
  '            {user?.firstName} {user?.lastName}',
  '          </div>',
  '          <button',
  '            onClick={onLogout}',
  '            className="w-full text-left px-3 py-2 rounded-lg text-sm font-medium text-red-600 hover:bg-red-50 transition"',
  '          >',
  '            \u0412\u044B\u0439\u0442\u0438',
  '          </button>',
  '        </div>',
  '      </aside>',
  '',
  '      {/* Content */}',
  '      <main className="flex-1 min-w-0">',
  '        <header className="h-14 bg-white border-b border-gray-200 flex items-center px-6">',
  '          <div className="text-sm text-gray-500">',
  '            {user?.role === "director" ? "\u0414\u0438\u0440\u0435\u043A\u0442\u043E\u0440" : "\u0410\u0434\u043C\u0438\u043D\u0438\u0441\u0442\u0440\u0430\u0442\u043E\u0440"}',
  '          </div>',
  '        </header>',
  '        <div className="p-6">',
  '          <Outlet />',
  '        </div>',
  '      </main>',
  '    </div>',
  '  );',
  '}',
  '',
].join("\n"));

// ============ src/components/RequireAuth.tsx ============
write("components/RequireAuth.tsx", [
  'import { Navigate, Outlet, useLocation } from "react-router-dom";',
  'import { useAuth } from "../auth/AuthContext";',
  '',
  'export default function RequireAuth() {',
  '  const { user, loading } = useAuth();',
  '  const location = useLocation();',
  '',
  '  if (loading) {',
  '    return (',
  '      <div className="min-h-screen flex items-center justify-center text-gray-500">',
  '        \u0417\u0430\u0433\u0440\u0443\u0437\u043A\u0430\u2026',
  '      </div>',
  '    );',
  '  }',
  '  if (!user) {',
  '    return <Navigate to="/login" state={{ from: location }} replace />;',
  '  }',
  '  return <Outlet />;',
  '}',
  '',
].join("\n"));

// ============ src/App.tsx (переписать) ============
write("App.tsx", [
  'import { Navigate, Route, Routes } from "react-router-dom";',
  'import { AuthProvider } from "./auth/AuthContext";',
  'import RequireAuth from "./components/RequireAuth";',
  'import AppLayout from "./layouts/AppLayout";',
  'import LoginPage from "./pages/LoginPage";',
  'import PlaceholderPage from "./pages/PlaceholderPage";',
  '',
  'export default function App() {',
  '  return (',
  '    <AuthProvider>',
  '      <Routes>',
  '        <Route path="/login" element={<LoginPage />} />',
  '',
  '        <Route element={<RequireAuth />}>',
  '          <Route element={<AppLayout />}>',
  '            <Route index element={<Navigate to="/orders" replace />} />',
  '            <Route path="/orders" element={<PlaceholderPage title="\u0417\u0430\u043A\u0430\u0437\u044B" />} />',
  '            <Route path="/clients" element={<PlaceholderPage title="\u041A\u043B\u0438\u0435\u043D\u0442\u044B" />} />',
  '            <Route path="/catalog" element={<PlaceholderPage title="\u0421\u043F\u0440\u0430\u0432\u043E\u0447\u043D\u0438\u043A\u0438" note="\u041F\u0435\u0440\u0441\u043E\u043D\u0430\u0436\u0438, \u0433\u0440\u0443\u043F\u043F\u044B, \u0441\u0442\u0430\u0432\u043A\u0438" />} />',
  '            <Route path="/finance" element={<PlaceholderPage title="\u0424\u0438\u043D\u0430\u043D\u0441\u044B" note="\u041F\u043E\u0441\u0442\u0443\u043F\u043B\u0435\u043D\u0438\u044F, \u0432\u044B\u043F\u043B\u0430\u0442\u044B, \u0440\u0430\u0441\u0445\u043E\u0434\u044B" />} />',
  '          </Route>',
  '        </Route>',
  '',
  '        <Route path="*" element={<Navigate to="/" replace />} />',
  '      </Routes>',
  '    </AuthProvider>',
  '  );',
  '}',
  '',
].join("\n"));

console.log("\nOK: \u0424\u0430\u0437\u0430 2 scaffolded");